### ISSUE TITLE
Applying own data and pytorch

### ISSUE THREAD

**Issue by alexxony** [fperdigon/DeepFilter#29]
I have 500 edf files of ecg. and I would like to apply your model on my data. 
They have a lot of electrode pop and bluetooth connections
Also I am familiar with pytorch.  

Can you help me  applying Your model ?

**Comment by fperdigon** [comment]
Hi @alexxony
Our model and deep learning pipeline use Keras/Tensorflow. We don't have projects of recoding the project or release a PyTorch version any time soon. 

However, you could use our code and pipeline to train our model then you can write a code for exporting the model + wights in ONNX format and import that in Pytorch to use it on your own signals.

Since your signals have different electrodes you can filter your signals with our model by filtering them each electrode at the time and merge the resulting signals at the end.

I wish you a good look at your project!!!

**Comment by fperdigon** [comment]
I am closing this since it's not really a code related issue
