### ISSUE TITLE
Error in training cell

### ISSUE THREAD

**Issue by therealthapa** [fperdigon/DeepFilter#30]
AttributeError: 'str' object has no attribute 'decode'

**Comment by fperdigon** [comment]
Hi, could you please elaborate on the issue? Also, provide more information
- link of the notebook (we have more than one in the repo)
- cell number
- Used platform (Google Colab, self-hosted, etc)

**Comment by fperdigon** [comment]
I was able to start the training, please see the image below. 
Please remember you need to reboot the runtime after the first cell and make sure that all the libraries were properly installed. Normally I will run the first cell and reboot the runtime up to 3 times to be sure all is working as expected.
![image](https://user-images.githubusercontent.com/13784296/152592700-9bb39a16-689d-4ec4-bf48-2f237652e159.png)

**Comment by fperdigon** [comment]
I was able to reproduce the error and also fixed it. The issue was related to h5py lib version installed by default in the Google Colab environment. This library is used to save and lather load the model's weights.

Adding **!pip install 'h5py==2.10.0' --force-reinstall** to the first call does the trick. But now some errors appear after running the first cell. They do not harm the proper functioning of the notebook so far.

![image](https://user-images.githubusercontent.com/13784296/152648718-be1440b0-20f3-4a5b-89c9-3c2eb9e2ea3e.png)

For now, the bug is fixed but to be honest, I am envisioning that unless Google Collab allows to setup a specific python environment it will be difficult to keep it running in the future.
@therealthapa thanks for the bug report!

**Comment by therealthapa** [comment]
Thank you @fperdigon . The code seems to work now. Have you trained for 100,000 epochs? It should take a lot of time though?

**Comment by Amrican10** [comment]
@fperdigon I have the same problem. I adjusted the runtime to be GPU. It runs well till the cell of training models and stops with (**AttributeError: 'str' object has no attribute 'decode'**). I tried to add "**!pip install 'h5py==2.10.0**' --force-reinstall" and it generates error in the first cell. 
What do you recommend to do to fix this issue?

**Comment by Amrican10** [comment]
This is a the exact error:
![image](https://user-images.githubusercontent.com/50168266/154194915-0a5475a3-377e-4ca0-9cbe-9c4285015f01.png)
